While executing file `Games/Thumgeon_II/main.py` an error occurred (<module> refers to the game file):

Traceback (most recent call last):
  File "launcher.py", line 307, in <module>
  File "main.py", line 9, in <module>
ImportError: can't import name Color
